services:
  - type: web
    name: flavorfusion-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://zeltrax:6B6Zvt2vkzw0AdCY@qrcode.ygptz.mongodb.net/?retryWrites=true&w=majority&appName=qrcode&dbName=qrcode
      - key: JWT_SECRET
        value: 18319e66f0f2818d99b83926a66e5c77672bec663b17d587fbfe3653d0de2fac
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: IMAGEKIT_PUBLIC_KEY
        value: public_+C8qAJu6ZKlhwQ6i0ZGfbNMa2Ho=
      - key: IMAGEKIT_PRIVATE_KEY
        value: private_YTyR3acLdo6ApVwMoyFIOxKAoIg=
      - key: IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/rwz4yhwit/
      - key: CLIENT_URL
        value: https://flavorfusion-2dr4afkh3-pratham7723s-projects.vercel.app
      - key: SERVER_URL
        value: https://flavorfusion-backend.onrender.com
